development:
  adapter: postgresql
  encoding: unicode
  database: agreelist_dev
  pool: 5
  username: hector
  password: contrh
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: agreelist_test
  pool: 5
  username: hector
  password: contrh
  host: localhost
